version: '2'

services:
  web:
    build: .
    image: local/reynolds
    environment:
      MIX_ENV: dev
      PORT: 4000
      DATABASE_URL: "${DATABASE_URL}"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    command: ["mix", "phoenix.server"]

  test:
    image: local/reynolds
    command: ["mix", "test"]
    environment:
      MIX_ENV: test
      PORT: 4001
      DATABASE_URL: postgres://admin:admin@postgres:5432/reynolds_test
    volumes:
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
