#!/usr/bin/env bash

set -eu

docker-compose up -d postgres
while true
do
  echo "Waiting for postgres to be ready..."
  docker-compose run --rm postgres psql ${DATABASE_URL%/*}/template1 -c select 1 > /dev/null 2>&1 \
    && break
done

docker-compose run --rm web mix do deps.get, compile, ecto.create, ecto.migrate
docker-compose ps
